logging:  config: classpath:logback-spring.xml

spring.datasource:
    url:  jdbc:mysql://localhost:3306/socialcrap_api?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  database: MYSQL
  show-sql: true
  generate-ddl: true
  properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.ddl-auto: none
      hibernate.hbm2ddl.auto: update
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext    
      
spring.servlet:
    multipart:
      max-file-size: 22MB
      max-request-size: 22MB
      enabled: true
      
server:
  port: 8080